//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.SmartRetention.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfesoresCursos
    {
        public int Id { get; set; }
        public int IdProfesor { get; set; }
        public int IdCurso { get; set; }
    }
}
