//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.SmartRetention.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EstudiantesRiesgo
    {
        public int IdEstudiante { get; set; }
        public string Estudiante { get; set; }
        public string Curso { get; set; }
        public int IdMatricula { get; set; }
        public Nullable<double> PorcentajeAsistencia { get; set; }
        public Nullable<decimal> UltimaNota { get; set; }
        public string NivelRiesgo { get; set; }
    }
}
